name: Update CCTV IPTV

on:
  schedule:
    - cron: '0 16 * * *'  # Runs every day at 16:00 UTC (Midnight Beijing Time)
  workflow_dispatch:      # Allows manual trigger

permissions:
  contents: write

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Update Script
        env:
          FOFA_EMAIL: ${{ secrets.FOFA_EMAIL }}
          FOFA_KEY: ${{ secrets.FOFA_KEY }}
        run: python update.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add cctv_live.m3u
          # Commit only if there are changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update CCTV IPTV sources" && git push)
